// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Field: typeof import('./src/components/art/Field.vue')['default']
    NeonTriangle: typeof import('./src/components/art/NeonTriangle.vue')['default']
    OpenInNew: typeof import('./src/components/OpenInNew.vue')['default']
  }
}

export { }
